Input string: Output string: 'ala ma k'ota
Input string: Output string: być 'albo ńe być 'oto jest pyt'ańe
Input string: Output string: ż'eby hr'ońić inform'acje zainteresow'ane p'aństwa podj'eły r'uwńeż dźał'ańa psyholog'iczne
Input string: Output string: marzn'eli bo ńe mj'eli silik'onu
Input string: Output string: pj'orun kul'isty wygl'ondem pszypom'ina śwjetl'istą k'ule o średń'icy od k'ilku do kilkudźeś'enću centym'etruf
Input string: Output string: r'enką
Input string: Output string: pewn'ego dńa zroz'umjesz że w ż'yću jest t'ylko j'eden uńiwers'alny j'enzyk ś'iła i matem'atyka
Input string: Output string: pszes'ada dwje l'aski dynam'itu to by b'yła pszes'ada
Input string: Output string: ruk r'ogi
Input string: Output string: r'ico ż'adnyh t'estuf jondr'owyh w b'aźe
Input string: 