#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B18"""

import sys
import re

REG_1 = r"^((Mt ([1-9]|(1[0-9])|(2[0-8])), ([1-9]|([1-9][0-9])))|"
REG_2 = r"(Mk ([1-9]|(1[0-6])), ([1-9]|([1-9][0-9])))|"
REG_3 = r"(Łk ([1-9]|(1[0-9])|(2[0-4])), ([1-9]|([1-9][0-9])))|"
REG_4 = r"(J ([1-9]|(1[0-9])|(2[0-2])), ([1-9]|([1-9][0-9]))))$"
REG = re.compile(REG_1+REG_2+REG_3+REG_4)
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
