#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B04"""

import sys
import re

REG = re.compile(r"^5{3}(( \d{3} \d{3})|(-\d{3}-\d{3}))$")
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
