Input string: Output string: Widzę księdza profesora Mateusza Kusia, jak rozmawia z doktorem inżynierem jak mu tam było.
Input string: Output string: profesor doktor habilitowany ksiądz magister inżynier
Input string: Output string: profesor habilitowany hahahaha
Input string: Output string: od profesora habilitowanego hahahaha
Input string: Output string: doktor Michał Rrrrrrrr
Input string: Output string: doktora Michała Rrrrrrrr
Input string: Output string: doktor Michał Rrrrrrrr
Input string: Output string: doktora Michała Rrrrrrrr
Input string: Output string: profesor Pasem Ratunkowym
Input string: Output string: profesorem Pasem Kaczmarkiem
Input string: Output string: doktor habilitowany Rups Koźlarski doktora habilitowanego Rups Koźlarskiego
Input string: Output string: dramat wyprof.
Input string: 