#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B24"""

import sys
import re

REG_1 = r"^([A-Z][a-z]*[b-z] [A-Z][a-z]+)$"
REG = re.compile(REG_1)
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
