#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B03"""

import sys
import re

REG = re.compile(r"^\d{3}-\d{3}-\d{2}-\d{2}$|^\d{3}-\d{2}-\d{2}-\d{3}$")
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
