#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B31"""

import sys
import re

REG_1 = r"^([qwrtpsdfghjklzxcvbnmłćż]*[aąeęioóuy][qwrtpsdfghjklzxcvbnmłćż]*)$"
REG = re.compile(REG_1)
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
