#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B39"""

import sys
import re

REG = re.compile(r"^\d{4}$")
REG_2 = re.compile(r"^(0{4}|1{4}|2{4}|3{4}|4{4}|5{4}|6{4}|7{4}|8{4}|9{4})$")
for line in sys.stdin:
    if re.match(REG, line):
        if re.match(REG_2, line):
            print "false"
        else:
            print "true"
    else:
        print "false"
