Input string: Output string: dwanaście tysięcy trzysta czterdzieści pięć
Input string: Output string: zero
Input string: Output string: minus dziewięćset dziewięćdziesiąt dziewięć milionów dziewięćset dziewięćdziesiąt dziewięć tysięcy dziewięćset dziewięćdziesiąt dziewięć
Input string: Output string: tysiąc osiemset dziewięć
Input string: Output string: minus dwanaście
Input string: Output string: trzy tysiące dziewięćdziesiąt osiem
Input string: Output string: trzy miliony
Input string: Output string: osiem
Input string: Output string: dwadzieścia dwa
Input string: Output string: milion jeden
Input string: 