Input string: Output string: Jaki człowiek wie, w którym roku urodził się Mozart?
Input string: Output string: Jaki człowiek wie, w którym roku urodził się Mozart?
Input string: Output string: Powiedz, jaki człowiek wie, w którym roku urodził się Mozart?
Input string: Output string: sprawa, odnośnie do której się pytam
Input string: Output string: Odnośnie do tego
Input string: Output string: do tyłu, tak cofnęli się wtedy
Input string: Output string: w każdym razie, człowiek, który grał na pianinie
Input string: Output string: cofnęliby się 31 stycznia
Input string: Output string: to był 1 października 2012
Input string: Output string: W każdym razie, stało się to 28 lutego
Input string: 