#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B26"""

import sys
import re

REG_1 = r"^(([+-]?[1-9][0-9]*)|(0))$"
REG = re.compile(REG_1)
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
