#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B37"""

import sys
import re

# N-NNN-NNN | NNN-NN-NN
REG_VAL = r"^((\(0?\d{2}\))|(0?\d{2})) ((\d-\d{3}-\d{3})|(\d{3}-\d{2}-\d{2}))$"
REG = re.compile(REG_VAL)
REG_2 = re.compile(r"\d{2}[ )]")
for line in sys.stdin:
    if re.match(REG, line):
        print re.search(REG_2, line).group(0)[:2]
    else:
        print "<NONE>"
