Input string: Output string: tej Czerwona bimba tej przyjechała i tej zielony autobus tej odjechał
Input string: Output string: tej Wiaruchna zakluczyła tej modrą kapustę tej
Input string: Output string: tej Ci dziwna tej wiaruchna to tej chyba macała tej się z tej głupim bez tej ścianę
Input string: Output string: tej Bimbą jechał tej i nadusił tej przycisk
Input string: Output string: tej Bejmy były tej zakluczone
Input string: Output string: tej Bimba dzisiaj tej odblablowała
Input string: 