#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B33"""

import sys
import re

REG_1 = r"^(([AGCT]+)|([AGCU]+))$"
REG = re.compile(REG_1)
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
