#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B09"""

import sys
import re

REG = re.compile(r".*[A-Z]\d{2}.*")
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
