#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie B30"""

import sys
import re

# -50 !?
REG_1 = r"^((-?([1-9]|([1-4][0-9])))|(0)|(-50))$"
REG = re.compile(REG_1)
for line in sys.stdin:
    if re.match(REG, line):
        print "true"
    else:
        print "false"
