#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""Zadanie A00"""

import sys

if len(sys.argv) < 2:
    print "Arguments are empty!"
else:
    STATES = []
    INPUT_TEXT = []
    KEY_COUNTER = 0
    KEY_MAP = dict()
    KEY_ACCEPT = []
    for line in sys.stdin:
        if line[0] != "#":
            val = line.rstrip().split()
            val_len = len(val)
            if val_len == 3:
                val[0] = int(val[0])
                val[1] = int(val[1])
                if val[0] not in STATES:
                    STATES.append(val[0])
                if val[1] not in STATES:
                    STATES.append(val[1])
                if val[2] not in KEY_MAP:
                    KEY_MAP[val[2]] = KEY_COUNTER
                    val[2] = KEY_COUNTER
                    KEY_COUNTER += 1
                else:
                    val[2] = KEY_MAP[val[2]]
                INPUT_TEXT.append(val)
            elif val_len == 1:
                val[0] = int(val[0])
                if val[0] not in KEY_ACCEPT:
                    KEY_ACCEPT.append(val[0])
    ALL_MAP = [[-1 for x in range(KEY_COUNTER)] for x in range(len(STATES))]
    for i in INPUT_TEXT:
        if ALL_MAP[i[0]][i[2]] == -1:
            ALL_MAP[i[0]][i[2]] = i[1]
        else:
            print "NON-DETERMINISTIC"
            sys.exit(0)
    FILE = open(sys.argv[1], "r")
    for i in FILE:
        i = i.rstrip()
        current = 0
        check = 1
        for char in i:
            if char in KEY_MAP:
                if ALL_MAP[current][KEY_MAP[char]] > -1:
                    current = ALL_MAP[current][KEY_MAP[char]]
                else:
                    check = 0
                    print "NO", i
                    break
            else:
                check = 0
                print "NO", i
                break
        if check:
            if current in KEY_ACCEPT:
                print "YES", i
            else:
                print "NO", i
    FILE.close()
